# asciinema
# Autogenerated from man page /usr/share/man/man1/asciinema.1.gz
complete -c asciinema -s c --description 'is what you want in most cases.'
complete -c asciinema -l stdin --description 'Enable stdin (keyboard) recording (see below).'
complete -c asciinema -l append --description 'Append to existing recording.'
complete -c asciinema -l raw --description 'Save raw STDOUT output, without timing information or other metadata.'
complete -c asciinema -l overwrite --description 'Overwrite the recording if it already exists.'
complete -c asciinema -l command --description 'Specify command to record, defaults to $SHELL.'
complete -c asciinema -s e -l env --description 'List of environment variables to capture, defaults to SHELL,TERM.'
complete -c asciinema -s t -l title --description 'Specify the title of the asciicast.'
complete -c asciinema -s i -l idle-time-limit --description 'Limit recorded terminal inactivity to max <sec> seconds.'
complete -c asciinema -s y -l yes --description 'Answer [lq]yes[rq] to all prompts (e. g.  upload confirmation).'
complete -c asciinema -s q -l quiet --description 'Be quiet, suppress all notices/warnings (implies -y) Stdin recording allows f…'
complete -c asciinema -s s -l speed --description 'Playback speed (can be fractional) cat <filename>.'

